application: whichisbetterhcde
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /.*
  script: main.application

- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: assets/favicon\.ico


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest
